name: lfg
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: BennyKok/lfg
      branch: main
      deploy_on_push: true
    http_port: 8766
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: LFG_HOST
        value: 0.0.0.0
      - key: LFG_PORT
        value: "8766"
      - key: LFG_REPOS_ROOT
        value: /data/repos
